[[redirects]]
  from = "/*"
  to = "https://mask-detection-api-diyso3zwua-uc.a.run.app/"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
